### ISSUE TITLE
random: Thanks and question

### ISSUE THREAD

**Issue by rafinskipg** [willianantunes/nextjs-playground#8]
hello @willianantunes thanks for this fantastic example.

I have some questions about your design that I need to understand and maybe you can help me with it.
- What is the benefit of using next-redux ? I guess on the client side is really useful for simplifying the logic. But how do you feel it to work for you with next?
- Why you choose to go away from the "standard" next structure and create a "src" folder? Does this complicate the deployment for you in services like "zeit.co" ?

Thanks!

**Comment by willianantunes** [comment]
You're welcome, @rafinskipg! I almost finished another playground project, but this time for C# and it's an API where you can play Tic Tac Toe (check this out [here](https://github.com/willianantunes/tic-tac-toe-csharp-playground)).

About your questions...

> What is the benefit of using next-redux ? I guess on the client side is really useful for simplifying the logic.

Looking [this PR](https://github.com/willianantunes/nextjs-playground/pull/2) where I implemented Redux, I believe I used `next-redux` to integrate Redux properly with Next.js because of some issues (I don't remember them well, but I had various), I even used [this boilerplate](https://github.com/CodementorIO/nextjs-redux-starter) project to get some lessons learned.

> But how do you feel it to work for you with next?

It's pretty straightforward. I can safely code backend and frontend sides with tests, so I believe it's OK and it wasn't problematic when I was testing it.

> Why you choose to go away from the "standard" next structure and create a "src" folder?

I use `src` just to concentrate the concrete implementation of the project there, I do this for every JS project I develop and this convention I borrowed from Java/Kotlin and Python (but in this case instead of `src` you would see [the name of the project](https://github.com/willianantunes/django-graphql-playground), like I did in C# above), it's easier to make newcomers understand the project as well.

> Does this complicate the deployment for you in services like "zeit.co"

[Next.js 9.1 support this approach](https://nextjs.org/blog/next-9-1#src-directory-support), so I believe it will work properly in [zeit.co](https://zeit.co/).

**Comment by rafinskipg** [comment]
Thank you @willianantunes
